# TODO: implement all of the unimplemented fields 

paths:
  output_path: ~
  youtube_cookie_filepath: /home/soulripper/assets/cookies.txt

download_behavior:
  youtube_only: False
  soulseek_only: False                                      # unimplemented
  max_retries: 5                                            # unimplemented
  inactive_download_timeout: 10                             # unimplemented

privacy:
  spotify_scope: "user-library-read user-read-private playlist-read-collaborative playlist-read-private"

debug:
  log: False                                                # unimplemented
  log_filepath: debug/log.txt                               # unimplemented
  db_echo: False

# TODO: all soulseek stuff too - also should write in api keys from .env file