# TODO: implement all of the unimplemented fields 

# NOTE: all paths must be absolute

paths:
  music_dir_root: /home/soulripper/debug/music                        # unimplemented
  output_path: /home/soulripper/debug/music
  youtube_cookie_filepath: /home/soulripper/assets/cookies.txt
  database_path: /home/soulripper/assets/soul.db

download_behavior:
  youtube_only: False
  soulseek_only: False                                                # unimplemented
  max_retries: 5                                                      # unimplemented
  inactive_download_timeout: 5                                        # unimplemented

audio:
  valid_extensions:
    - ".mp3"
    - ".flac"
    - ".wav"

privacy:
  spotify_scope: "user-library-read user-read-private playlist-read-collaborative playlist-read-private"

debug:
  log: True                                                           # unimplemented
  log_level: DEBUG                                                    # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_filepath: /home/soulripper/debug/log.txt                        # unimplemented
  db_echo: False